### ISSUE TITLE
Use JSON rather than JS file for data

### ISSUE THREAD

**Issue by AntoineJT** [bryc/quizlang#1]
word_lists.js must be a JSON file and not a JS file

**Comment by bryc** [comment]
That won't work because JSON only works in an online environment. This app (and most of my apps) are designed to work locally (double click .html file and run using file:// protocol) as well as online. I only break this compatibility when absolutely necessary.

The JS file is technically a JSON file anyway (JSON is just a limited subset of JS objects), which is loaded into memory directly rather than XMLHttpRequest.
